language: python
python:
#  - "3.6"      # current default Python on Travis CI
#  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
  # PyPy versions
  - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0# command to run tests
install:
  - pip install numpy
  - pip install .
script:
  - pytest